site_name: wiki-ICM
site_description: Material de estudio para la carrera de Ingeneria Civil Matematica.
site_url: https://wiki-icm.github.io/


nav:
  - Home: index.md
  - Primer Año :
      - Malla 2021: a121.md
      - Malla 2025: a125.md
  - Segundo Año : a2.md
  - Tercer Año : a3.md
  - Cuarto Año : a4.md
  - Quinto Año : a5.md
  - Sexto Año : a6.md
  - Electivos:
        - Electivos Libres: electivos/libres.md
        - Electivos Obligatorios:
            - Analisis Numerico y Ecuaciones Diferenciales: electivos/obligatorios/num.md
            - Matematicas Discretas: electivos/obligatorios/discreta.md
            - Estadistica y Procesos Estocasticos: electivos/obligatorios/estadistica.md
            - Optimizacion y Control: electivos/obligatorios/opti.md

        - Electivos Opcionales:
            - Analisis Numerico y Ecuaciones Diferenciales: electivos/opcionales/num.md
            - Matematicas Discretas: electivos/opcionales/discreta.md
            - Estadistica y Procesos Estocasticos: electivos/opcionales/estadistica.md
            - Optimizacion y Control: electivos/opcionales/opti.md

  - Otros: ot.md
  





theme: 
  name: material
  logo: assets/logof.png
  features:
    - navigation.instant.preview
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tracking
    - toc.integrate
    - navigation.expand


markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:      
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - meta-descriptions:
      min_length: 50
      max_length: 160
      trim: true
      fallback_if_short: true
  -cards:
    background_color: "#1a1a1a"
    text_color: "#ffffff"
